using System;

public enum ProjectileType {
	AM39Missile,
	AS20Missile,
	AS30Missile,
	ASM1Missile,
	BaeAlarmMissile,
	BaeSeaSkuaMissile,
	BullpupAMissile,
	BullpupBMissile,
	C801Missile,
	Gabriel3Missile,
	HarmMissile,
	HarpoonMissile,
	KeglerMissile,
	Kh23MAMissile,
	Kh23MBMissile,
	Kh25MMissile,
	Kh29MMissile,
	Kh29TMissile,
	Kh35Missile,
	Kh58Missile,
	Kh59TMissile,
	KilterMissile,
	KitolovMissile,
	KrasnopolMissile,
	MartelArmMissile,
	MartelMissile,
	MarteMark2Missile,
	MaverickMissile,
	MBBKormoranMissile,
	Missile1Missile,
	Missile2Missile,
	Missile3Missile,
	MjoelnirMissile,
	NordMissile,
	PenguinMissile,
	RaptorMissile,
	ShrikeMissile,
	TinyTimMissile,
	UbanMissile,
	YakhontMissile
}

